#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "esp_err.h"

#define LABCAPSULE_VERSION "1.3.0-alpha"
#define LABCAPSULE_MEDIA_MAX_FPS 8U
#define LABCAPSULE_PET_BUBBLE_WIDTH 216U
#define LABCAPSULE_PET_BUBBLE_HEIGHT 64U
#define LABCAPSULE_PET_BUBBLE_BYTES \
    (LABCAPSULE_PET_BUBBLE_WIDTH * LABCAPSULE_PET_BUBBLE_HEIGHT / 8U)

typedef enum {
    LABCAPSULE_MEDIA_RAW565 = 0,
    LABCAPSULE_MEDIA_RLE565,
    LABCAPSULE_MEDIA_RGB332,
    LABCAPSULE_MEDIA_RLE332,
    LABCAPSULE_MEDIA_DELTA332,
} labcapsule_media_encoding_t;

/** Apply an APK/BLE/HTTP screen action such as HOME, TEST, UP or BL_ON. */
esp_err_t labcapsule_remote_action(const char *action, char *response, size_t response_size);

/** Build the compact JSON document returned by Wi-Fi and BLE status endpoints. */
void labcapsule_build_status_json(char *buffer, size_t buffer_size);

/** Build allocation-free device fragments for the constrained NimBLE host task. */
void labcapsule_build_ble_device_json(char *buffer, size_t buffer_size);
void labcapsule_build_hardware_json(char *buffer, size_t buffer_size);

/** Stable public identifier derived from the base MAC, e.g. lc-001122aabbcc. */
const char *labcapsule_device_id(void);

/** Select the canonical character and whether current media is its device proxy. */
esp_err_t labcapsule_set_character_identity(const char *character_id, bool proxy_enabled);

/** Replace the 1-bit 216x64 dialogue mask shown by the pet scene. */
esp_err_t labcapsule_set_pet_bubble(const uint8_t *payload, size_t payload_size);

/** Select the persisted wallpaper after a successful upload. */
void labcapsule_show_wallpaper(void);

/** Receive one transient RGB565 frame. GIF animation is decoded by the controller. */
esp_err_t labcapsule_media_frame_begin(size_t payload_size);
esp_err_t labcapsule_media_region_begin(size_t payload_size, uint16_t x, uint16_t y,
                                        uint16_t width, uint16_t height,
                                        labcapsule_media_encoding_t encoding);
esp_err_t labcapsule_media_frame_write(const uint8_t *data, size_t length);
esp_err_t labcapsule_media_frame_finish(uint32_t duration_ms);
void labcapsule_media_frame_abort(void);

/** Control the one persisted device-side GIF/video clip. */
esp_err_t labcapsule_media_clip_start(void);
void labcapsule_media_clip_stop(void);
esp_err_t labcapsule_media_clip_set_fps(uint8_t fps);
bool labcapsule_media_clip_playing(void);
uint8_t labcapsule_media_clip_fps(void);

/** Set PWM backlight brightness in the inclusive 0..100 range. */
esp_err_t labcapsule_set_brightness(uint8_t percent);

/** Apply the persisted wallpaper/HUD composition style. Values are inclusive 0..100. */
esp_err_t labcapsule_set_visual_style(uint8_t preset, uint8_t wallpaper_opacity,
                                      uint8_t panel_opacity, uint8_t hud_opacity);

/** Validate and start an experiment generated by the app/AI protocol. */
esp_err_t labcapsule_start_experiment(uint32_t rate_hz, uint32_t duration_seconds);

/** Switch between the low-activity information dashboard and experiment console. */
esp_err_t labcapsule_set_idle_mode(bool idle);

/** Update the short ASCII notification shown by the idle dashboard. */
esp_err_t labcapsule_set_idle_notice(const char *title, const char *message);
