#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>

#include "esp_err.h"
#include "labcapsule_control.h"

#define MEDIA_STORE_MAX_CLIP_BYTES (6U * 1024U * 1024U)

typedef struct {
    labcapsule_media_encoding_t encoding;
    uint16_t x;
    uint16_t y;
    uint16_t width;
    uint16_t height;
    size_t payload_size;
} media_store_frame_t;

typedef struct {
    FILE *file;
    uint32_t interval_ms;
    uint32_t loop_frame_count;
    uint32_t loop_index;
    long loop_offset;
    size_t file_size;
} media_store_reader_t;

/** Use the already mounted /offline FAT volume for one replaceable current clip. */
esp_err_t media_store_init(void);
bool media_store_clip_available(void);
size_t media_store_clip_size(void);

/** Upload to a temporary file and atomically replace the prior current clip on finish. */
esp_err_t media_store_upload_begin(size_t expected_size);
esp_err_t media_store_upload_write(const uint8_t *data, size_t length);
esp_err_t media_store_upload_finish(void);
void media_store_upload_abort(void);
esp_err_t media_store_delete_clip(void);

/** Sequential reader for the big-endian LCG4 container generated by the clients. */
esp_err_t media_store_reader_open(media_store_reader_t *reader);
esp_err_t media_store_reader_bootstrap(media_store_reader_t *reader,
                                       media_store_frame_t *frame,
                                       uint8_t *payload, size_t capacity);
esp_err_t media_store_reader_next(media_store_reader_t *reader,
                                  media_store_frame_t *frame,
                                  uint8_t *payload, size_t capacity);
void media_store_reader_close(media_store_reader_t *reader);
